In [15]:
import numpy as np
import torch
from torch.utils import data

def synthetic_data(w, b, num_examples):
    """生成y = Xw + b + 噪声"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape(-1, 1)

def load_array(data_arrays, batch_size, is_train=True):
    """构建一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle= is_train)

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)
data_iter = load_array((features, labels), batch_size= 10)



In [36]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [37]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr = 0.005)

In [38]:
num_epochs = 10
print(net[0].weight)
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'end=epoch {epoch + 1}, loss {l:f}')
print(net[0].weight)

Parameter containing:
tensor([[0.0132, 0.0198]], requires_grad=True)
end=epoch 1, loss 4.637529
end=epoch 2, loss 0.675119
end=epoch 3, loss 0.098369
end=epoch 4, loss 0.014413
end=epoch 5, loss 0.002178
end=epoch 6, loss 0.000396
end=epoch 7, loss 0.000138
end=epoch 8, loss 0.000100
end=epoch 9, loss 0.000094
end=epoch 10, loss 0.000094
Parameter containing:
tensor([[ 1.9994, -3.4000]], requires_grad=True)
