In [27]:
import torch
import numpy as np
import pandas as pd

In [ ]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

In [31]:
X = torch.arange(12).reshape(3,4)
print(X[:,1:3])
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a+b

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])


array([[0, 1],
       [1, 2],
       [2, 3]])

In [37]:
X = torch.arange(12).reshape(3,4)
print(X[:,1:3])
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad = True)
y = x * x
u = y.detach()
z = u * y + 5
z.sum().backward()
x.grad

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])


tensor([  2.,  16.,  54., 128.])

In [9]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [14]:
import pandas as pd

data = pd.read_csv(data_file)
data

,NumRooms,Alley,Price
0,NaN,Pave,127500
1,2.0,NaN,106000
2,4.0,NaN,178100
3,NaN,NaN,140000


In [26]:
x = torch.tensor([1,2,3,4.0], requires_grad = True)
y = x * x
y.backward(torch.tensor([1, 1, 1, 1]))
x.grad

tensor([2., 4., 6., 8.])